apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskblog
  name: flaskblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskblog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskblog
    spec:
      containers:
      - image: joeygeofrey/fblog:5
        name: flaskblog
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskblog
